### PR TITLE
Update required node version to match the one installed

### PR DESCRIPTION
**Pull request by internalsystemerror**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Dockerfile installed node v18, however package.json is using node v17. This PR updates the latter to ensure there is no confusion by developers or by the tools.

There are also a couple of removal instances of unused lines of code, which I can undo if requested. In this vein, I also added double quoting inside the shell scripts to prevent globbing and word splitting.

### CODE REVIEW

**Comment by internalsystemerror** [comment]
The target/lib version of ECMAscript to use was taken from: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping. Node v18 will _probably_ support `es2022`, however https://node.green/#ES2022 reports that this is only 97% implemented.

**Review by Ocramius — APPROVED** [review]
🚢 build is also green

**Comment by Ocramius** [comment]
Well, post-merge build is red 😩

**Comment by Ocramius** [comment]
Nvm, seems like a `docker pull` limit issue, unrelated to this

**Comment by internalsystemerror** [comment]
Odd that it was green in the PR.

I suspect you're correct, but https://github.com/laminas/laminas-ci-matrix-action/tree/1.14.x/tests/code-check-deprecated-exclusion-via-config is the failing test on both release branches.

**Pull request merged**
