### PR TITLE
Change default stable PHP from 7.4 to 8.0

### PR DESCRIPTION
**Pull request by gsteel**

### CODE REVIEW

**Review by internalsystemerror — APPROVED** [review]

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Comment by gsteel** [comment]
But CI didn't run at all!

**Comment by Ocramius** [comment]
😱

Ok, something is off in GitHub Actions today.

**Comment by internalsystemerror** [comment]
https://github.com/laminas/laminas-ci-matrix-action/pull/164 may help... I wonder if because npm 9 is in the latest nodejs version, this might be preventing the matrix action from running?

**Pull request merged**
