### PR TITLE
Switch from PHPDBG to just "PHP" for coverage and mutation tests

### PR DESCRIPTION
**Pull request by Ocramius**
This change is needed for https://github.com/laminas/laminas-continuous-integration-action/pull/148

Ref: https://github.com/laminas/laminas-continuous-integration-action/issues/130
Ref: https://github.com/sebastianbergmann/php-code-coverage/issues/945
Ref: https://github.com/sebastianbergmann/php-code-coverage/commit/c304be7d8aa00a71cf8fe763a4b92e14d3f67f4d

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### CODE REVIEW

**Review by internalsystemerror — APPROVED** [review]

**Comment by internalsystemerror** [comment]
Changes look good, obv we need to get the checks green but I thought they would have been already? https://github.com/laminas/laminas-continuous-integration-action/pull/148 shouldnt be needed for that?

**Comment by boesing** [comment]
I wonder if we should explicitly enable `pcov` extension for phpunit runs rather than having it enabled by-default.

I can't see anything related to `pcov` in this PR; how is it enabled?

**Comment by gsteel** [comment]
I thought the CI failures were my fault, but it looks like a regression in `sergeysova/jq-action@v2.3.0` introduced here https://github.com/sergeysova/jq-action/pull/9

See #190

**Comment by Ocramius** [comment]
> I can't see anything related to `pcov` in this PR; how is it enabled?

I'll run the built container and check: very good point!

**Comment by Ocramius** [comment]
I'll merge this into `2.0.0` too.

**Comment by internalsystemerror** [comment]
This might need rebasing, and then hopefully thanks to https://github.com/laminas/laminas-ci-matrix-action/pull/191 the checks should be green. If not then something else has gone wrong here.

**Pull request merged**
