### PR TITLE
PHPStan tooling detection

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| New Feature   | yes

### Description

Introduce PHPStan

### CODE REVIEW

**Comment by boesing** [comment]
FYI: Had to refactor a bit since `eslint` did not pass due to maximum line-length per-file of `100` lines 🫠

**Review by gsteel — APPROVED** [review]
Thanks @boesing - This looks perfect afaict 👍

**Comment by alexmerlin** [comment]
@boesing Could you also fix the small error reported under the [Unchanged files with check annotations](https://github.com/laminas/laminas-ci-matrix-action/pull/318/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) section?

**Comment by gsteel** [comment]
It's been several months so I'm merging and releasing this without further review.

**Comment by Ocramius** [comment]
Just dropping it here, but apparently, I get PHPStan runs even for repos that don't have PHPStan? 

https://github.com/Roave/SecurityAdvisoriesBuilder/actions/runs/12371968284/job/34529270030?pr=759

**Comment by gsteel** [comment]
> Just dropping it here, but apparently, I get PHPStan runs even for repos that don't have PHPStan?

@Ocramius 

That's expected if you've got a PHPStan config file in the root directory no? Same as Psalm, PHPUnit etc 

https://github.com/Roave/SecurityAdvisoriesBuilder/blob/latest/phpstan.neon.dist

**Comment by Ocramius** [comment]
ZOMG I'm blind :facepalm:

**Pull request merged**
